### ISSUE TITLE
可以试一试这两个任务

### ISSUE THREAD

**Issue by linhaowei1** [SouthwestWindQ/ML-pytorch#1]
1. 写一个Autoencoder，数据集为MNIST，使用MLP/CNN。
2. 用CNN或者RNN做一个文本分类的任务，数据集见https://github.com/linhaowei1/Learning-Learning/tree/main/textCNN/text_classification_data

**Comment by SouthwestWindQ** [comment]
好的好的👌🏼

**Comment by SouthwestWindQ** [comment]
> 1. 写一个Autoencoder，数据集为MNIST，使用MLP/CNN。
> 2. 用CNN或者RNN做一个文本分类的任务，数据集见https://github.com/linhaowei1/Learning-Learning/tree/main/textCNN/text_classification_data

全部完成啦！
任务1. https://github.com/SouthwestWindQ/ML-pytorch/tree/main/AutoEncoder
任务2. https://github.com/SouthwestWindQ/ML-pytorch/tree/main/Text%20Classification
